apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ServiceAccount
      name: grafana
    patch: |
      - op: add
        path: /metadata/annotations/iam.gke.io~1gcp-service-account
        value: grafana-production@revenu-gateway-production.iam.gserviceaccount.com
  - target:
      kind: Deployment
      name: grafana
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "https://dashboard.revenu.com.br/"
  - target:
      kind: Ingress
      name: grafana
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: dashboard.revenu.com.br
      - op: add
        path: /spec/ingressClassName
        value: gce
      - op: add
        path: /metadata/annotations/kubernetes.io~1ingress.global-static-ip-name
        value: grafana-prod-ip
  - target:
      kind: Deployment
      name: grafana
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
