apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: grafana-frontend
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: revenu-platform
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
