apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: grafana-cert
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: revenu-platform
spec:
  domains:
    - dashboard.allenty.io
