apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: revenu-platform
  annotations: {}
  # iam.gke.io/gcp-service-account set via overlay per environment
