apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ServiceAccount
      name: grafana
    patch: |
      - op: add
        path: /metadata/annotations/iam.gke.io~1gcp-service-account
        value: grafana-dev@revenu-gateway-dev.iam.gserviceaccount.com
  - target:
      kind: Deployment
      name: grafana
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "https://gateway.allenty.io/dashboard/"
